"""Initial migration

Revision ID: 83540b6c4efc
Revises: 
Create Date: 2024-07-26 22:59:17.940188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83540b6c4efc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('pens_made', sa.Integer(), nullable=True),
    sa.Column('pens_att', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('cards_yellow', sa.Integer(), nullable=True),
    sa.Column('cards_red', sa.Integer(), nullable=True),
    sa.Column('touches', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('npxg', sa.Float(), nullable=True),
    sa.Column('xg_assist', sa.Float(), nullable=True),
    sa.Column('sca', sa.Float(), nullable=True),
    sa.Column('gca', sa.Float(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('passes_pct', sa.Float(), nullable=True),
    sa.Column('progressive_passes', sa.Integer(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('progressive_carries', sa.Integer(), nullable=True),
    sa.Column('take_ons', sa.Integer(), nullable=True),
    sa.Column('take_ons_won', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('home_away', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('competition', sa.String(), nullable=True),
    sa.Column('goal_involvements', sa.Integer(), nullable=True),
    sa.Column('xg_involvements', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_player'), 'player_stats', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_player'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
