from database import Base
from sqlalchemy import Float, Column, Integer, String, Date


class PlayerStatsDB(Base):
    __tablename__ = 'player_stats'
    id = Column(Integer, primary_key=True, index=True)
    player = Column(String, index=True)
    position = Column(String)
    age = Column(String)
    minutes = Column(Integer)
    goals = Column(Integer)
    assists = Column(Integer)
    pens_made = Column(Integer)
    pens_att = Column(Integer)
    shots = Column(Integer)
    shots_on_target = Column(Integer)
    cards_yellow = Column(Integer)
    cards_red = Column(Integer)
    touches = Column(Integer)
    tackles = Column(Integer)
    interceptions = Column(Integer)
    blocks = Column(Integer)
    xg = Column(Float)
    npxg = Column(Float)
    xg_assist = Column(Float)
    shot_creating_actions = Column(Float)
    goal_creating_actions = Column(Float)
    passes = Column(Integer)
    passes_pct = Column(Float)
    progressive_passes = Column(Integer)
    carries = Column(Integer)
    progressive_carries = Column(Integer)
    take_ons = Column(Integer)
    take_ons_won = Column(Integer)
    team = Column(String)
    opponent = Column(String)
    home_away = Column(String)
    date = Column(Date)
    competition = Column(String)
    goal_involvements = Column(Integer)
    xg_involvements = Column(Integer)
